version: "3.9"

services:
  python-api:
    build: ./pythonAPI
    container_name: python-api
    ports:
      - "8000:8000"
    environment:
      - API_ENV=docker
    restart: unless-stopped

  angular-ui:
    build: ./angularUI
    container_name: angular-ui
    ports:
      - "4200:80"
    depends_on:
      - python-api
    restart: unless-stopped
